In [159]:
import pandas as pd
import numpy as np
import seaborn as sbs
import matplotlib.pyplot as mlt

In [160]:
df = pd.read_csv('spam.csv')
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [161]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [162]:
df.shape

(5572, 2)

In [163]:
# train test split
from sklearn.model_selection import train_test_split

In [164]:
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.Category, test_size=.2, random_state=1)

In [165]:
X_train

1642    Hi , where are you? We're at  and they're not ...
2899          If you r @ home then come down within 5 min
480     When're you guys getting back? G said you were...
3485    Tell my  bad character which u Dnt lik in me. ...
157                           I'm leaving my house now...
                              ...                        
905     We're all getting worried over here, derek and...
5192    Oh oh... Den muz change plan liao... Go back h...
3980    CERI U REBEL! SWEET DREAMZ ME LITTLE BUDDY!! C...
235     Text & meet someone sexy today. U can find a d...
5157                              K k:) sms chat with me.
Name: Message, Length: 4457, dtype: object

In [166]:
X_train[5:11]

4430    Hey they r not watching movie tonight so i'll ...
2625                          S da..al r above  &lt;#&gt;
5365    Camera - You are awarded a SiPix Digital Camer...
4067    Fyi I'm gonna call you sporadically starting a...
3120                             Stop knowing me so well!
1044    Mmm thats better now i got a roast down me! i’...
Name: Message, dtype: object

In [167]:
# Doing back of ward

In [168]:
X_train.shape

(4457,)

In [169]:
X_test.shape

(1115,)

In [170]:
X_train.value_counts

<bound method IndexOpsMixin.value_counts of 1642    Hi , where are you? We're at  and they're not ...
2899          If you r @ home then come down within 5 min
480     When're you guys getting back? G said you were...
3485    Tell my  bad character which u Dnt lik in me. ...
157                           I'm leaving my house now...
                              ...                        
905     We're all getting worried over here, derek and...
5192    Oh oh... Den muz change plan liao... Go back h...
3980    CERI U REBEL! SWEET DREAMZ ME LITTLE BUDDY!! C...
235     Text & meet someone sexy today. U can find a d...
5157                              K k:) sms chat with me.
Name: Message, Length: 4457, dtype: object>

<h2 style="color: green"> Create bag of wards representation using CountVector </h2>

In [171]:
from sklearn.feature_extraction.text import CountVectorizer

In [172]:
v = CountVectorizer()

In [176]:
emails = [
    'upto 20% discount reward!',
    'Hey buddy, discount upto'
]
emails_cv = v.fit_transform(emails)
emails_cv

<2x6 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [177]:
emails_cv.toarray()

array([[1, 0, 1, 0, 1, 1],
       [0, 1, 1, 1, 0, 1]])

In [178]:
v.get_feature_names_out()

array(['20', 'buddy', 'discount', 'hey', 'reward', 'upto'], dtype=object)

In [179]:
pd.DataFrame(emails_cv.toarray(), columns=v.get_feature_names_out())

20  buddy  discount  hey  reward  upto
0   1      0         1    0       1     1
1   0      1         1    1       0     1

In [180]:
V = CountVectorizer()
X_train_cv = V.fit_transform(X_train.values)
X_train_cv

<4457x7711 sparse matrix of type '<class 'numpy.int64'>'
	with 58978 stored elements in Compressed Sparse Row format>

In [181]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [182]:
V.get_feature_names_out()

array(['00', '000', '008704050406', ..., 'zyada', 'èn', '〨ud'],
      dtype=object)

In [183]:
X_train_cv.shape

(4457, 7711)

In [184]:
pd.DataFrame(X_train_cv.toarray(), columns= V.get_feature_names_out())

00  000  008704050406  0121  01223585236  01223585334  0125698789  02  \
0      0    0             0     0            0            0           0   0   
1      0    0             0     0            0            0           0   0   
2      0    0             0     0            0            0           0   0   
3      0    0             0     0            0            0           0   0   
4      0    0             0     0            0            0           0   0   
...   ..  ...           ...   ...          ...          ...         ...  ..   
4452   0    0             0     0            0            0           0   0   
4453   0    0             0     0            0            0           0   0   
4454   0    0             0     0            0            0           0   0   
4455   0    0             0     0            0            0           0   0   
4456   0    0             0     0            0            0           0   0   

      0207  02072069400  ...  zed  zeros  zhong  zindgi  zoe  zoom  zouk  \
0        0            0  ...    0      0      0       0    0     0     0   
1        0            0  ...    0      0      0       0    0     0     0   
2        0            0  ...    0      0      0       0    0     0     0   
3        0            0  ...    0      0      0       0    0     0     0   
4        0            0  ...    0      0      0       0    0     0     0   
...    ...          ...  ...  ...    ...    ...     ...  ...   ...   ...   
4452     0            0  ...    0      0      0       0    0     0     0   
4453     0            0  ...    0      0      0       0    0     0     0   
4454     0            0  ...    0      0      0       0    0     0     0   
4455     0            0  ...    0      0      0       0    0     0     0   
4456     0            0  ...    0      0      0       0    0     0     0   

      zyada  èn  〨ud  
0         0   0    0  
1         0   0    0  
2         0   0    0  
3         0   0    0  
4         0   0    0  
...     ...  ..  ...  
4452      0   0    0  
4453      0   0    0  
4454      0   0    0  
4455      0   0    0  
4456      0   0    0  

[4457 rows x 7711 columns]

In [ ]:
V.vocabulary_

In [ ]:
# Build the Model

In [185]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [186]:
X_test_cv = V.transform(X_test)

In [187]:
X_test_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [188]:
X_test_cv.toarray().shape

(1115, 7711)

In [189]:
V.get_feature_names_out()

array(['00', '000', '008704050406', ..., 'zyada', 'èn', '〨ud'],
      dtype=object)

In [190]:
model.score(X_test_cv, y_test)

0.989237668161435

In [191]:
from sklearn.metrics import classification_report
y_pred = model.predict(X_test_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         ham       0.99      1.00      0.99       968
        spam       0.98      0.94      0.96       147

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [192]:
my_mail = [
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss the reward',
    'hello alamin, hope you are doing well call me your free time!!'
]

In [193]:
my_mail_cv = V.transform(my_mail)
my_mail_cv.toarray().shape

(2, 7711)

In [194]:
model.predict(my_mail_cv)

array(['spam', 'ham'], dtype='<U4')