In [2]:
import pandas as pd
import numpy as np

In [3]:
indx = 'r1 r2 r3 r4 r5 r6 r7 r8 r9 r10'.split()
col = 'c1 c2 c3 c4 c5 c6 c7 c8 c9 c10'.split()

indx, col

(['r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9', 'r10'],
 ['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10'])

In [4]:
array_2d = np.arange(100)
array_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
array_2d = array_2d.reshape(10, 10)

In [6]:
df = pd.DataFrame(data = array_2d, index = indx, columns = col)
df

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [7]:
df[['c1', 'c2']]

c1  c2
r1    0   1
r2   10  11
r3   20  21
r4   30  31
r5   40  41
r6   50  51
r7   60  61
r8   70  71
r9   80  81
r10  90  91

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
df['c11'] = df['c1'] + df['c10']
df

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c11
r1    0   1   2   3   4   5   6   7   8    9    9
r2   10  11  12  13  14  15  16  17  18   19   29
r3   20  21  22  23  24  25  26  27  28   29   49
r4   30  31  32  33  34  35  36  37  38   39   69
r5   40  41  42  43  44  45  46  47  48   49   89
r6   50  51  52  53  54  55  56  57  58   59  109
r7   60  61  62  63  64  65  66  67  68   69  129
r8   70  71  72  73  74  75  76  77  78   79  149
r9   80  81  82  83  84  85  86  87  88   89  169
r10  90  91  92  93  94  95  96  97  98   99  189

In [10]:
df = df.rename(columns={'c11' : 'c1+c10'})
df

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c10
r1    0   1   2   3   4   5   6   7   8    9       9
r2   10  11  12  13  14  15  16  17  18   19      29
r3   20  21  22  23  24  25  26  27  28   29      49
r4   30  31  32  33  34  35  36  37  38   39      69
r5   40  41  42  43  44  45  46  47  48   49      89
r6   50  51  52  53  54  55  56  57  58   59     109
r7   60  61  62  63  64  65  66  67  68   69     129
r8   70  71  72  73  74  75  76  77  78   79     149
r9   80  81  82  83  84  85  86  87  88   89     169
r10  90  91  92  93  94  95  96  97  98   99     189

In [11]:
df['new'] = 'A'
df

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c10 new
r1    0   1   2   3   4   5   6   7   8    9       9   A
r2   10  11  12  13  14  15  16  17  18   19      29   A
r3   20  21  22  23  24  25  26  27  28   29      49   A
r4   30  31  32  33  34  35  36  37  38   39      69   A
r5   40  41  42  43  44  45  46  47  48   49      89   A
r6   50  51  52  53  54  55  56  57  58   59     109   A
r7   60  61  62  63  64  65  66  67  68   69     129   A
r8   70  71  72  73  74  75  76  77  78   79     149   A
r9   80  81  82  83  84  85  86  87  88   89     169   A
r10  90  91  92  93  94  95  96  97  98   99     189   A

In [12]:
# df.drop('new', axis=1, inplace=True)
df

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c10 new
r1    0   1   2   3   4   5   6   7   8    9       9   A
r2   10  11  12  13  14  15  16  17  18   19      29   A
r3   20  21  22  23  24  25  26  27  28   29      49   A
r4   30  31  32  33  34  35  36  37  38   39      69   A
r5   40  41  42  43  44  45  46  47  48   49      89   A
r6   50  51  52  53  54  55  56  57  58   59     109   A
r7   60  61  62  63  64  65  66  67  68   69     129   A
r8   70  71  72  73  74  75  76  77  78   79     149   A
r9   80  81  82  83  84  85  86  87  88   89     169   A
r10  90  91  92  93  94  95  96  97  98   99     189   A

In [13]:
df.loc[['r3', 'r4']]

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c10 new
r3  20  21  22  23  24  25  26  27  28   29      49   A
r4  30  31  32  33  34  35  36  37  38   39      69   A

In [14]:
df.iloc[[9]] # i stands for inplec index

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c10 new
r10  90  91  92  93  94  95  96  97  98   99     189   A

In [15]:
df.loc[['r1', 'r2'], ['c1', 'c2']]

c1  c2
r1   0   1
r2  10  11

In [16]:
df.loc[['r1', 'r5'], ['c2', 'c7']]

c2  c7
r1   1   6
r5  41  46

In [18]:
df

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c10 new
r1    0   1   2   3   4   5   6   7   8    9       9   A
r2   10  11  12  13  14  15  16  17  18   19      29   A
r3   20  21  22  23  24  25  26  27  28   29      49   A
r4   30  31  32  33  34  35  36  37  38   39      69   A
r5   40  41  42  43  44  45  46  47  48   49      89   A
r6   50  51  52  53  54  55  56  57  58   59     109   A
r7   60  61  62  63  64  65  66  67  68   69     129   A
r8   70  71  72  73  74  75  76  77  78   79     149   A
r9   80  81  82  83  84  85  86  87  88   89     169   A
r10  90  91  92  93  94  95  96  97  98   99     189   A

In [ ]:
new_df = df % 4 == 0
new_df

c1     c2     c3     c4     c5     c6     c7     c8     c9    c10  \
r1    True  False  False  False   True  False  False  False   True  False   
r2   False  False   True  False  False  False   True  False  False  False   
r3    True  False  False  False   True  False  False  False   True  False   
r4   False  False   True  False  False  False   True  False  False  False   
r5    True  False  False  False   True  False  False  False   True  False   
r6   False  False   True  False  False  False   True  False  False  False   
r7    True  False  False  False   True  False  False  False   True  False   
r8   False  False   True  False  False  False   True  False  False  False   
r9    True  False  False  False   True  False  False  False   True  False   
r10  False  False   True  False  False  False   True  False  False  False   

     c1 c10  
r1    False  
r2    False  
r3    False  
r4    False  
r5    False  
r6    False  
r7    False  
r8    False  
r9    False  
r10   False

In [22]:
df[df['c1'] >= 10]

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c10 new
r2   10  11  12  13  14  15  16  17  18   19      29   A
r3   20  21  22  23  24  25  26  27  28   29      49   A
r4   30  31  32  33  34  35  36  37  38   39      69   A
r5   40  41  42  43  44  45  46  47  48   49      89   A
r6   50  51  52  53  54  55  56  57  58   59     109   A
r7   60  61  62  63  64  65  66  67  68   69     129   A
r8   70  71  72  73  74  75  76  77  78   79     149   A
r9   80  81  82  83  84  85  86  87  88   89     169   A
r10  90  91  92  93  94  95  96  97  98   99     189   A

In [24]:
df[df['c2'] > 11] [['c1', 'c4', 'c5']]

c1  c4  c5
r3   20  23  24
r4   30  33  34
r5   40  43  44
r6   50  53  54
r7   60  63  64
r8   70  73  74
r9   80  83  84
r10  90  93  94

In [25]:
df[df['c1'] >= 20].loc[['r3', 'r4']]

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c10 new
r3  20  21  22  23  24  25  26  27  28   29      49   A
r4  30  31  32  33  34  35  36  37  38   39      69   A

In [27]:
result = df[df['c1']==70]
result

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c10 new
r8  70  71  72  73  74  75  76  77  78   79     149   A

In [30]:
df[(df['c1'] > 60) & (df['c2'] > 80)]

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c10 new
r9   80  81  82  83  84  85  86  87  88   89     169   A
r10  90  91  92  93  94  95  96  97  98   99     189   A

In [32]:
df.head(4)

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c10 new
r1   0   1   2   3   4   5   6   7   8    9       9   A
r2  10  11  12  13  14  15  16  17  18   19      29   A
r3  20  21  22  23  24  25  26  27  28   29      49   A
r4  30  31  32  33  34  35  36  37  38   39      69   A

In [33]:
df.tail(5)

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c10 new
r6   50  51  52  53  54  55  56  57  58   59     109   A
r7   60  61  62  63  64  65  66  67  68   69     129   A
r8   70  71  72  73  74  75  76  77  78   79     149   A
r9   80  81  82  83  84  85  86  87  88   89     169   A
r10  90  91  92  93  94  95  96  97  98   99     189   A

In [35]:
df.describe()

c1         c2         c3         c4         c5         c6  \
count  10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   
mean   45.000000  46.000000  47.000000  48.000000  49.000000  50.000000   
std    30.276504  30.276504  30.276504  30.276504  30.276504  30.276504   
min     0.000000   1.000000   2.000000   3.000000   4.000000   5.000000   
25%    22.500000  23.500000  24.500000  25.500000  26.500000  27.500000   
50%    45.000000  46.000000  47.000000  48.000000  49.000000  50.000000   
75%    67.500000  68.500000  69.500000  70.500000  71.500000  72.500000   
max    90.000000  91.000000  92.000000  93.000000  94.000000  95.000000   

              c7         c8         c9        c10      c1+c10  
count  10.000000  10.000000  10.000000  10.000000   10.000000  
mean   51.000000  52.000000  53.000000  54.000000   99.000000  
std    30.276504  30.276504  30.276504  30.276504   60.553007  
min     6.000000   7.000000   8.000000   9.000000    9.000000  
25%    28.500000  29.500000  30.500000  31.500000   54.000000  
50%    51.000000  52.000000  53.000000  54.000000   99.000000  
75%    73.500000  74.500000  75.500000  76.500000  144.000000  
max    96.000000  97.000000  98.000000  99.000000  189.000000

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, r1 to r10
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   c1      10 non-null     int64 
 1   c2      10 non-null     int64 
 2   c3      10 non-null     int64 
 3   c4      10 non-null     int64 
 4   c5      10 non-null     int64 
 5   c6      10 non-null     int64 
 6   c7      10 non-null     int64 
 7   c8      10 non-null     int64 
 8   c9      10 non-null     int64 
 9   c10     10 non-null     int64 
 10  c1+c10  10 non-null     int64 
 11  new     10 non-null     object
dtypes: int64(11), object(1)
memory usage: 1.3+ KB


In [38]:
my_list = np.array([-1,0,1])
my_list

array([-1,  0,  1])

In [40]:
array_2dd = np.arange(100, 0, -1)
array_2dd

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])