# 2D Array Slicing and Indexing

In [1]:
import numpy as np

In [4]:
arr_2d = np.arange(24).reshape(6, 4)
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
arr_2d[3]

array([12, 13, 14, 15])

In [8]:
arr_2d[4, 1]

17

In [10]:
arr_2d[-2]

array([16, 17, 18, 19])

In [12]:
arr_2d[1:3, :2]

array([[4, 5],
       [8, 9]])

In [14]:
arr_2d[:3, :3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [15]:
arr_2d[[1, 2, 5]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [20, 21, 22, 23]])

In [17]:
arr_2d[:, [3]]

array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23]])