In [1]:
import numpy as np

In [2]:
arr = np.arange(5)
arr2 = np.arange(5)

In [3]:
arr + arr2

array([0, 2, 4, 6, 8])

In [4]:
arr - arr2

array([0, 0, 0, 0, 0])

In [5]:
arr * arr2

array([ 0,  1,  4,  9, 16])

In [6]:
arr / arr2

/var/folders/5s/lt7ld7zd4p3ccg26y8vp2r4r0000gn/T/ipykernel_34778/1444868932.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr2


array([nan,  1.,  1.,  1.,  1.])

In [7]:
arr ** 2

array([ 0,  1,  4,  9, 16])