In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[3] = 99
arr

array([ 0,  1,  2, 99,  4,  5,  6,  7,  8,  9])

In [5]:
arr[: 3] = 33
arr

array([33, 33, 33, 99,  4,  5,  6,  7,  8,  9])

In [9]:
arr_2d = np.ones((4, 4))
arr_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
arr_2d[1] = 99
arr_2d

array([[ 1.,  1.,  1.,  1.],
       [99., 99., 99., 99.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [11]:
arr_2d + 300

array([[301., 301., 301., 301.],
       [399., 399., 399., 399.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.]])

In [16]:
a = np.array([[1, 3, 4], [22, 22, 22], [44, 44, 44]])
b = np.array([ 1, 1, 1])


In [17]:
print(a + b)

[[ 2  4  5]
 [23 23 23]
 [45 45 45]]
