In [1]:
import numpy as np

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [4]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [5]:
arr_2d = np.arange(30).reshape(6, 5)

In [6]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [7]:
arr_2d.sum()

435

In [8]:
arr_2d.sum(axis= 0)

array([75, 81, 87, 93, 99])

In [9]:
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110, 135])

In [10]:
arr_2d.std()

8.65544144839919