In [1]:
import numpy as np
x = [1, 3, 5, 6]
print(x)
print(type(x))

[1, 3, 5, 6]
<class 'list'>


In [2]:
# arr = np.array([1,4, 5, 6])
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)



[[1 2 3]
 [4 5 6]]


In [3]:
print('how')

how


In [4]:
def sum(a, b):
    return a + b


print(sum(1,2))



3


In [5]:
print(arr*2)

[[ 2  4  6]
 [ 8 10 12]]


In [7]:
my_list = [1, 2, 4]

In [9]:
my_arr = np.array(my_list)
my_arr

array([1, 2, 4])

In [10]:
my_ar_list = [[1,2,4], [3, 5, 6], [7, 8, 9]]
np.array(my_ar_list)

array([[1, 2, 4],
       [3, 5, 6],
       [7, 8, 9]])

# NUMPY arange FUNCTION

In [11]:
make_arr = np.arange(50)
make_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [13]:
arr_range = np.arange(3, 15, 2)
arr_range

array([ 3,  5,  7,  9, 11, 13])

In [14]:
flot_arr = np.arange(1, 15, 0.2, dtype=float)
flot_arr

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,
        5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,
        7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,
        9.8, 10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8,
       12. , 12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. ,
       14.2, 14.4, 14.6, 14.8])

In [100]:
np.linspace(0, 0, 5)

array([0., 0., 0., 0., 0.])

# LINspace-Function-IN-NUMPAY 

In [16]:
newSlice = np.linspace(1, 15, 50, retstep=True)
newSlice

(array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
         2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
         3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
         5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
         6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
         8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
         9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
        11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
        12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
        13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ]),
 0.2857142857142857)

In [17]:
flot_arr.shape

(70,)

In [25]:
ab = np.arange(0, 16, 1)
ab

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
new_ab = ab.reshape(4, 4)
new_ab

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
ab.reshape(2, 4, 2), ab.reshape(4, 2, 2)

(array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[12, 13],
         [14, 15]]]))

In [33]:
new_ab.shape

(4, 4)

In [35]:
new_ab = new_ab.reshape(1, 16)
new_ab

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [37]:
new_ab.reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [44]:
ran_num = np.random.rand(5) * 10
ran_num

array([8.16187443, 5.34522378, 2.89528632, 0.04296433, 8.3587123 ])

In [54]:
rn = np.random.randint(2, 100, size=(2, 2))
rn

array([[64, 40],
       [15, 27]])

In [60]:
np.random.randint(2, 456, 10)

array([325, 325,  76, 202, 166, 102,  76, 137, 104, 109])

In [61]:
np.random.randint(1, 100, 4).reshape(2,2)

array([[80, 56],
       [ 7, 75]])

In [59]:
np.random.randint(100, 500, 20).reshape(2, 2, 5)

array([[[234, 203, 207, 105, 430],
        [391, 276, 448, 315, 347]],

       [[222, 449, 158, 221, 285],
        [358, 305, 180, 414, 303]]])

In [67]:
new_rn = np.random.randint(1, 500, 15)
new_rn

array([293,  60, 493, 322, 351,  95, 315, 448, 327, 149, 342, 360, 364,
       371, 255])

In [73]:
new_rn.min(), new_rn.max(), new_rn.argmax(), new_rn.argmin()

(60, 493, 2, 1)

In [75]:
arr_arange = np.arange(16)
arr_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [77]:
arr_arange.size

16

In [79]:
arr_arange.shape

(16,)

In [80]:
arr_arange.dtype

dtype('int64')

In [83]:
arr_arange.itemsize

8

In [85]:
arr_arange.reshape(2, 4, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [87]:
arr_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [89]:
arr_arange.shape

(16,)

In [91]:
arr_arange.shape = (4, 4)

In [93]:
arr_arange.shape

(4, 4)

In [95]:
arr_arange

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [97]:
arr_arange = arr_arange.reshape(1, 16)
arr_arange

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])